//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ImgCmp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ImgCmp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImgCmp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImgCmp() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImgCmpLibPINVOKE.delete_ImgCmp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ImgCmp() : this(ImgCmpLibPINVOKE.new_ImgCmp(), true) {
  }

  public vector_ImgDiff CompareImages(string ref_image, string test_image) {
    vector_ImgDiff ret = new vector_ImgDiff(ImgCmpLibPINVOKE.ImgCmp_CompareImages(swigCPtr, ref_image, test_image), true);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
