//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vector_ImgDiff : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<ImgDiff>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vector_ImgDiff(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vector_ImgDiff obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vector_ImgDiff() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ImgCmpLibPINVOKE.delete_vector_ImgDiff(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vector_ImgDiff(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (ImgDiff element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ImgDiff this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(ImgDiff[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(ImgDiff[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, ImgDiff[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<ImgDiff> global::System.Collections.Generic.IEnumerable<ImgDiff>.GetEnumerator() {
    return new vector_ImgDiffEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vector_ImgDiffEnumerator(this);
  }

  public vector_ImgDiffEnumerator GetEnumerator() {
    return new vector_ImgDiffEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vector_ImgDiffEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<ImgDiff>
  {
    private vector_ImgDiff collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vector_ImgDiffEnumerator(vector_ImgDiff collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ImgDiff Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (ImgDiff)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    ImgCmpLibPINVOKE.vector_ImgDiff_Clear(swigCPtr);
  }

  public void Add(ImgDiff x) {
    ImgCmpLibPINVOKE.vector_ImgDiff_Add(swigCPtr, ImgDiff.getCPtr(x));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = ImgCmpLibPINVOKE.vector_ImgDiff_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = ImgCmpLibPINVOKE.vector_ImgDiff_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    ImgCmpLibPINVOKE.vector_ImgDiff_reserve(swigCPtr, n);
  }

  public vector_ImgDiff() : this(ImgCmpLibPINVOKE.new_vector_ImgDiff__SWIG_0(), true) {
  }

  public vector_ImgDiff(vector_ImgDiff other) : this(ImgCmpLibPINVOKE.new_vector_ImgDiff__SWIG_1(vector_ImgDiff.getCPtr(other)), true) {
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ImgDiff(int capacity) : this(ImgCmpLibPINVOKE.new_vector_ImgDiff__SWIG_2(capacity), true) {
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  private ImgDiff getitemcopy(int index) {
    ImgDiff ret = new ImgDiff(ImgCmpLibPINVOKE.vector_ImgDiff_getitemcopy(swigCPtr, index), true);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ImgDiff getitem(int index) {
    ImgDiff ret = new ImgDiff(ImgCmpLibPINVOKE.vector_ImgDiff_getitem(swigCPtr, index), false);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ImgDiff val) {
    ImgCmpLibPINVOKE.vector_ImgDiff_setitem(swigCPtr, index, ImgDiff.getCPtr(val));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vector_ImgDiff values) {
    ImgCmpLibPINVOKE.vector_ImgDiff_AddRange(swigCPtr, vector_ImgDiff.getCPtr(values));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public vector_ImgDiff GetRange(int index, int count) {
    global::System.IntPtr cPtr = ImgCmpLibPINVOKE.vector_ImgDiff_GetRange(swigCPtr, index, count);
    vector_ImgDiff ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ImgDiff(cPtr, true);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ImgDiff x) {
    ImgCmpLibPINVOKE.vector_ImgDiff_Insert(swigCPtr, index, ImgDiff.getCPtr(x));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vector_ImgDiff values) {
    ImgCmpLibPINVOKE.vector_ImgDiff_InsertRange(swigCPtr, index, vector_ImgDiff.getCPtr(values));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    ImgCmpLibPINVOKE.vector_ImgDiff_RemoveAt(swigCPtr, index);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    ImgCmpLibPINVOKE.vector_ImgDiff_RemoveRange(swigCPtr, index, count);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vector_ImgDiff Repeat(ImgDiff value, int count) {
    global::System.IntPtr cPtr = ImgCmpLibPINVOKE.vector_ImgDiff_Repeat(ImgDiff.getCPtr(value), count);
    vector_ImgDiff ret = (cPtr == global::System.IntPtr.Zero) ? null : new vector_ImgDiff(cPtr, true);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    ImgCmpLibPINVOKE.vector_ImgDiff_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    ImgCmpLibPINVOKE.vector_ImgDiff_Reverse__SWIG_1(swigCPtr, index, count);
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vector_ImgDiff values) {
    ImgCmpLibPINVOKE.vector_ImgDiff_SetRange(swigCPtr, index, vector_ImgDiff.getCPtr(values));
    if (ImgCmpLibPINVOKE.SWIGPendingException.Pending) throw ImgCmpLibPINVOKE.SWIGPendingException.Retrieve();
  }

}
